## Inheritence
- super class /grand Parent class
- sub class/Parent class
- child class
- Acqring properities from Parent classes
- 3 types of inheritence
    - single level inheritence
    - Multilevel inheritence
    - Multiline inheritence
    


## single level Inheritence

In [6]:
class teacher():
    def f1(self):
        print("we are in f1")
class student():
    def f2(self):
        print("we are in f2")
# create a object
o=teacher()
o.f1()
o1=student()
o1.f2()

we are in f1
we are in f2


In [8]:
class teacher(): 
    def f1(self):
        print("we are in f1")
class student(teacher):# the student class inher the properties from teacher class
    def f2(self):
        print("we are in f2")
obj=student()
obj.f1() # f1 fuction is under parent class
obj.f2()

we are in f1
we are in f2


## Multilevel Inheritence


In [13]:
class A(): #super class
    def f1(self):
        print("we are in f1")
class B(A):#sub class
    def f2(self):
        print("we are in f2")
class C(B):#child class
    def f3(self):
        print("we are in f3")
obj= C()
obj.f3()
obj.f1()
obj.f2()

we are in f3
we are in f1
we are in f2


## Multiple Inheretence

In [16]:
class A(): #super class
    def f1(self):
        print("we are in f1")
class B():#sub class
    def f2(self):
        print("we are in f2")
class C(A,B):#child class
    def f3(self):
        print("we are in f3")
x=C()
x.f3()
x.f2()
x.f1()

we are in f3
we are in f2
we are in f1


In [17]:
dir(x)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'f1',
 'f2',
 'f3']

In [22]:
class A(): #super class
    def f1(self):
        print("we are in f1")
class B():#sub class
    def f2(self):
        print("we are in f2")
class C(A,B):#child class
    def f3(self):
        super().f1()
        print("we are in f3")
        super().f2()
x=C()
x.f3()
#x.f2()
#x.f1()

we are in f1
we are in f3
we are in f2


## Packages and Modules in OOPs
- package
    - collection of modules
- module
    - A .py file with  collection of methods
- method
    - A block of code in a function

In [1]:
import oops_module

In [2]:
dir(oops_module)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'barch2',
 'barch3',
 'brach1']

In [3]:
help(oops_module.brach1)

Help on class brach1 in module oops_module:

class brach1(builtins.object)
 |  Methods defined here:
 |  
 |  cse(self)
 |  
 |  ece(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [4]:
ob1=oops_module.brach1()
ob1

In [5]:
#dir(ob1)

In [6]:
ob1.ece()

we are ece students


In [7]:
help(ob1.cse)

Help on method cse in module oops_module:

cse() method of oops_module.brach1 instance



In [9]:
ob1.cse()

we ARE cse students


In [13]:
ob2=oops_module.barch3()

In [15]:
#dir(ob2)

In [16]:
ob2.python()

we ARE python students


In [17]:
ob2.apssdc()

we are apssdc students


## Python libraries for Datascience;
1. Numpy
2. Pandas
3. Matplotlib
4. Searborn

## Numpy
-  Numerical Python
- Arrays
    - single dimension array
    - 2 dimension array
    - multi dimension array
- Linear Algebra,Ft,Materics
-  2005 by Travis Oliphat
    

In [19]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
import numpy

In [22]:
import numpy as np
np.__version__

'1.18.1'

In [23]:
from numpy import *

In [24]:
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [26]:
# create array
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [29]:
print(ndim(x))# dimensions of array

1


In [33]:
print(shape(x))# no of columns and rows

(4,)


In [34]:
print(size(x))# no of elements

4


In [36]:
#help(numpy.shape)

# 2D array

In [37]:
import numpy as np
x=np.array([[1,2,3],[3,4,5]])
print(x)
print(ndim(x))

[[1 2 3]
 [3 4 5]]
2


In [39]:
shape(x)# no of rows and no of columns

(2, 3)

In [40]:
size(x)

6

## 3D-array

In [ ]:
import numpy as np
x=np.array([[[1,2,3],[3,5,7],[7,8,5]]])
print(x)
print